author: 'Tomasz Krzysztof Zieleniewski'
branding:
  icon: 'calendar'
  color: 'blue'
description: "Output repository timestamps - created at, pushed at and updated at."
name: "Repository Timestamps"

inputs:
  github-token:
    default: ${{ github.token }}
    description: 'A GitHub token used for making requests to GitHub APIs'
    required: false

outputs:
  created-at:
    description: 'Created at timestamp'
    value: ${{ steps.timestamps.outputs.created-at }}
  pushed-at:
    description: 'Pushed at timestamp'
    value: ${{ steps.timestamps.outputs.pushed-at }}
  updated-at:
    description: 'Updated at timestamp'
    value: ${{ steps.timestamps.outputs.updated-at }}

runs:
  using: composite
  steps:
    - id: timestamps
      run: |
        REPOSITORY_URL=$(echo ${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY})
        echo "::debug::Fetching repository resource from ${REPOSITORY_URL}"
        DATES=$(curl ${REPOSITORY_URL} \
        -H "Authorization: token ${{ github.token }}" | jq "[.created_at, .pushed_at, .updated_at]")
        echo "::debug::Repository dates ${DATES}"

        CREATED_AT_DATE=$(echo ${DATES} | jq -r .[0])
        echo "::debug::Created at date ${CREATED_AT_DATE}"
        CREATED_AT_TIMESTAMP=$(date -d "${CREATED_AT_DATE}" +%s)
        echo "::debug::Created at timestamp ${CREATED_AT_TIMESTAMP}"
        echo "::set-output name=created-at::${CREATED_AT_TIMESTAMP}"

        PUSHED_AT_DATE=$(echo ${DATES} | jq -r .[1])
        echo "::debug::Pushed at date ${PUSHED_AT_DATE}"
        PUSHED_AT_TIMESTAMP=$(date -d "${PUSHED_AT_DATE}" +%s)
        echo "::debug::Pushed at timestamp ${PUSHED_AT_TIMESTAMP}"
        echo "::set-output name=pushed-at::${PUSHED_AT_TIMESTAMP}"

        UPDATED_AT_DATE=$(echo ${DATES} | jq -r .[2])
        echo "::debug::Updated at date ${UPDATED_AT_DATE}"
        UPDATED_AT_TIMESTAMP=$(date -d "${UPDATED_AT_DATE}" +%s)
        echo "::debug::Updated at timestamp ${UPDATED_AT_TIMESTAMP}"
        echo "::set-output name=updated-at::${UPDATED_AT_TIMESTAMP}"
        env
      shell: bash
