author: 'Tomasz Krzysztof Zieleniewski'
branding:
  icon: 'calendar'
  color: 'blue'
description: "Repository dates"
name: "Repository dates"

inputs:
  created-at-enabled:
    description: 'Whether or not to determine the created at date'
    default: 'true'
    required: false
  github-token:
    description: "A GitHub token used for making requests to Github's API"
    default: ${{ github.token }}

outputs:
  created-at:
    description: 'Created at date'
    value: ${{ steps.created-at.outputs.date }}

runs:
  using: composite
  steps:
    - id: created-at
      if: inputs.created-at-enabled == 'true'
      run: |
        env
        REPOSITORY_URL=$(echo ${GITHUB_API_URL}/repos/tzieleniewski/github-action-repository-dates)
        echo repository ${REPOSITORY_URL}
        CREATED_AT=$(curl ${REPOSITORY_URL} \
        -H "Authorization: token ${{ github.token }}" | jq -r .created_at)
        echo date ${CREATED_AT}
        echo "::set-output name=date::${CREATED_AT}"
      shell: bash
