name: Test

on: push

jobs:
  creation-disabled:
    name: Does not set creation timestamp when disabled
    runs-on: ubuntu-latest
    steps:
      - name: given
        uses: actions/checkout@v2
      - name: when
        id: when
        uses: ./
        with:
          creation-enabled: 'false'
      - name: then
        if: steps.when.outputs.creation-timestamp != ''
        run: exit 1
        continue-on-error: true
  creation-enabled:
    name: Sets creation timestamp by default
    runs-on: ubuntu-latest
    steps:
      - name: given
        uses: actions/checkout@v2
      - name: when
        id: when
        uses: ./
      - name: then
        if: steps.when.outputs.creation-timestamp == ''
        run: exit 1
        continue-on-error: true
